export const AUTH_MESSAGES = {
  USERNAME_REQUIRED: 'Username is required',
  PASSWORD_REQUIRED: 'Password is required',
  DUMMY_USER: 'dummyuser',
  DUMMY_PASSWORD: '1234578910',
  AUTHENTICATION_FAILED: 'Authentication failed.',
  FORBIDDEN: 'Forbidden.',
  SUCCESSFUL_LOGIN: 'User has been successfully Logged-In.',
  SUCCESSFUL_SIGNUP: 'User has been successfully created.',
  SUCCESSFUL_SIGNOUT: 'User has been successfully signed out.',
  ERROR_PROCESSING_REQUEST: 'An error occurred while processing your request.',
  AUTH_USER: 'Authenticating User',
  OBJECT_LOADED_IN_SESSION: 'User Object loaded in Session Object:',
  AUTH_FAILED: 'Authentication failed:',
  CREATING_NEW_USER: 'Creating a new user',
  SIGNING_OUT_USER: 'Signing out a user',
  CHECKING_AUTHENTICATION: 'Checking authentication',
  CHECKING_USER_IF_AUTHENTICATION: 'Check if the user is authenticated',
  ERROR_IN_SESSION_ENDPOINT: 'Error in session endpoint:',
  INVALID_CREDENTIALS: 'Invalid credentials',
  TOKEN_NAME_TEXT: 'TOKEN_NAME',
  PRODUCTION: 'production',
  CREDENTAILS_TAKEN: 'Credentials already taken',
  SOMETHING_WENT_WRONG: 'Something went wrong',
};
